---
title: "Lógica y conjuntos"
subtitle: "Certeza y validez-Tablas de certeza" 
author: "Profesor: Gustavo Ahumada"
output:
  pdf_document: default
  html_document:
    df_print: paged
  theme: united
  html_notebook: default
---


# 3 Certeza y validez

## 3.5 Demostración condicional

Al llegar a este punto en el estudio de la Lógica estamos en condiciones
de realizar algunas demostraciones complicadas. Sin embargo, hay algunas
deducciones muy simples que no es posible efectuarlas con las reglas introducidas. Un ejemplo de una conclusión obvia que no se puede deducir todavía es la siguiente:

- Si José gana, entonces Luis es segundo.
- Si Carlos es segundo, entonces Luis no es segundo.
- Por tanto, si Carlos es segundo, entonces José no gana

Simbolicemos este razonamiento para decidir si somos o no capaces de demostrar su validez:
Sea
P = José gana
Q = Luis es segundo
R = Carlos es segundo.

\begin{align*}
\textrm{ } & P \rightarrow Q \\
\textrm{ } & R \rightarrow \neg{Q} \\
& \cline{1-2} \\
\textrm{ } & R \rightarrow \neg{P} \\
\end{align*}

Las reglas que se conocen no son suficientes para deducir la conclusión en
este razonamiento. También sería imposible encontrar una asignación de certeza en la que las premisas fueran ciertas y la conclusión falsa. Para que la conclusión sea falsa R y P han de ser ambas ciertas. Pero entonces, una u
otra de las premisas es falsa cualquiera que sea el valor de la asignación
de certeza dado a Q. Para deducir la conclusión, que es válida, se necesita
una regla que no ha sido introducida hasta ahora.

**La regla de la premisa**,  P,permite introducir una nueva premisa en una demostración siempre que se desee. Ésta puede ser cualquier proposición que se elija. Aunque parezca absurdo, se debe tener en cuenta que cada razonamiento lógico se apoya en todas /as premisas que utiliza. Si se introduce una premisa nueva, entonces cualquier conclusión que se deduzca del conjunto total de premisas, se apoyará sobre todas estas premisas y no sólo sobre el conjunto original de las mismas. **No es posible utilizar la regla P para deducir precisamente cualquier conclusión de un conjunto de premisas dad**.


El ejemplo dado anteriormente permite presentar un caso del nuevo uso de la **regla P**. En la línea (3) se introduce una nueva premisa **R**. A partir de esta línea hacia abajo se observa que la demostración se ha corrido varios espacios hacia la derecha

\begin{align*}
\textrm{ (1) } & P \rightarrow Q & && P  \\
\textrm{ (2) } & R \rightarrow \neg{Q} & && P  \\
\textrm{ (3) } && R  && RP \\
\textrm{ (4) } && \neg{Q}  && PP2,3 \\
\textrm{ (5) } && \neg{P}  && TT1,4 \\
\end{align*}

Se podría resumir la idea total en esta deducción diciendo que de las premisas originales, si se agrega la **R**, entonces se puede llegar a la conclusión $\neg{P}$. Esta idea está muy próxima a la de la nueva regla que se va a introducir y que permitirá completar la deducción en el razonamiento original hasta llegar a la conclusión. Considerando el razonamiento se ve que se intenta demostrar la proposición $R \rightarrow \neg{P}$.

Esta nueva regla, la regla de la **demostración condicional** (CP) se enuncia
como sigue:

Si es posible deducir una proposición **S** de otra proposición **R** y un conjunto de premisas, entonces se puede deducir sólo del conjunto de premisas la proposición condicional $R \rightarrow S$.

\begin{align*}
\textrm{ (1) } & P \rightarrow Q & && P  \\
\textrm{ (2) } & R \rightarrow \neg{Q} & && P  \\
\textrm{ (3) } && R  && P \\
\textrm{ (4) } && \neg{Q}  && PP2,3 \\
\textrm{ (5) } && \neg{P}  && TT1,4 \\
\textrm{ (6) } & R \rightarrow \neg{P} & && CP3,5 \\
\end{align*}

**Una buena estrategia a seguir es ésta**: Si la conclusión deseada de un razonamiento es una proposición condicional, añadiremos el antecedente como
nueva premisa, correremos la demostración varios lugares hacia la derecha
y finalmente trataremos de deducir el consecuente del conjunto original de
premisas más la premisa añadida.

**Ejemplo**. Demostrar: $P \rightarrow (\neg{Q} \rightarrow R)$

\begin{align*}
\textrm{ (1) } & S \land (\neg{P} \lor M) & && && P  \\
\textrm{ (2) } & M \rightarrow Q \lor R & && && P  \\
\textrm{ (3) } & \neg{P} \lor M & && && S1 \\
\textrm{ (4) } && P  && && P \\
\textrm{ (5) } && M  && && TP3,4 \\
\textrm{ (6) } &&&& \neg{Q}  && P \\
\textrm{ (7) } &&&& Q \lor R  && PP2,5 \\
\textrm{ (8) }  &&&& R  && TP6,7 \\
\textrm{ (9) } && \neg{Q} \rightarrow R  && && CP7,8 \\
\textrm{ (10) } & P \rightarrow (\neg{Q} \rightarrow R) & && && CP4,9  \\
\end{align*}


# 4 Tablas de certeza

## 4.1 Tablas de certeza

Un método en general más conveniente que el diagrama para analizar los
valores de certeza de proposiciones, es el de poner todas las posibilidades
de certeza o falsedad en forma de una tabla. En efecto, todas las reglas
de certeza funcional que se utilizan para proposiciones moleculares pueden
resumirse en forma de tabla.

**Negación**
\begin{align*}
\begin{tabular}{ c c } 
 P & $\neg{P}$ \\
  \hline
 C & F \\ 
 F & F  \\
\end{tabular}
\end{align*}

**Conjunción**
\begin{align*}
\begin{tabular}{ c c c } 
 P & Q & $P \land Q$ \\
  \hline
 C & C & C \\ 
 C & F & F  \\
 F & C & F  \\ 
 F & F & F  \\ 
\end{tabular}
\end{align*}

**Disjunción**
\begin{align*}
\begin{tabular}{ c c c } 
 P & Q & $P \lor Q$ \\
  \hline
 C & C & C \\ 
 C & F & C  \\
 F & C & C  \\ 
 F & F & F  \\ 
\end{tabular}
\end{align*}

**Condicional**
\begin{align*}
\begin{tabular}{ c c c } 
 P & Q & $P \rightarrow Q$ \\
  \hline
 C & C & C \\ 
 C & F & F  \\
 F & C & C  \\ 
 F & F & C  \\ 
\end{tabular}
\end{align*}

**Equivalencia**
\begin{align*}
\begin{tabular}{ c c c } 
 P & Q & $P \leftrightarrow Q$ \\
  \hline
 C & C & C \\ 
 C & F & F  \\
 F & C & F  \\ 
 F & F & C  \\ 
\end{tabular}
\end{align*}

En estas tablas se hallan resumidas todas las reglas de aplicación estudiadas. Si se tiene duda sobre alguna de estas reglas se pueden utilizar entonces estas tablas como tablas de referencia.

*Las tablas de certeza proporcionan un método mecánico para comprobar la validez de cada regla de inferencia*.

**El método de comprobar cada inferencia es el siguiente**:

1. Se escriben todas las combinaciones posibles de valores de certeza para las proposiciones atómicas incluidas en el ejemplo.^[En caso de tener dos proposiciones atómicas, y puesto que para cada una de ellas hay dos posibles valores de certeza, el número de líneas en la tabla de certeza será $2^{2}$. Entonces, el número de lineas de una tabla de certeza se determina con la siguiente formula: $2^{n}$, donde $n$ es el número de proposiciones atómicas.]

2. Se determinan los valores de certeza para todas las premisas y de la conclusión del razonamiento.

3. Se buscan las líneas que presentan todas las premisas como proposiciones ciertas; si la conclusión es también cierta para cada una de estas líneas, entonces el razonamiento es válido. Pero si hay alguna línea para la que todas las premisas son ciertas y la conclusión es falsa, el razonamiento no es válido y la conclusión no es una consecuencia lógica.

**Ejemplo**. Regla modus tollendo ponens

\begin{align*}
\begin{tabular}{ c c c c } 
 P & Q & $P \lor Q$ & $\neg{P}$ \\
  \hline
 C & C & C & F \\ 
 C & F & C & F  \\
 F & \textcolor{red}{C} & \textcolor{red}{C} & \textcolor{red}{C}  \\ 
 F & F & F & C  \\ 
\end{tabular}
\end{align*}

Para presentar un contraste con la inferencia válida del *modus tollendo
ponerts* consideremos el error de afirmar el consecuente, discutido en el
capítulo anterior. Lo que se pretende es mostrar cómo se puede utilizar el
análisis de las tablas de certeza para demostrar que se trata de un error. Esta inferencia errónea tiene la forma

\begin{align*}
\textrm{ } & P \rightarrow Q \\
\textrm{ } & Q \\
& \cline{1-2} \\
\textrm{ } & P \\
\end{align*}

Mediante el análisis de las tablas de verdad para demostrar el error de la infeencia anterior.

\begin{align*}
\begin{tabular}{ c c c } 
 P & Q & $P \rightarrow Q$  \\
  \hline
 \textcolor{red}{C} & \textcolor{red}{C} & \textcolor{red}{C}  \\ 
 C & F & F  \\
 \textcolor{blue}{F} & \textcolor{blue}{C} & \textcolor{blue}{C}  \\ 
 F & F & C  \\ 
\end{tabular}
\end{align*}

Es importante comprender exactamente el motivo por el cual la tabla
de certeza muestra que esta inferencia es errónea. En la línea (3) se observa
que P es falsa y Q es verdadera. Si se eligen dos proposiciones atómicas
cualesquiera que tengan respectivamente estos valores de certeza, se pueden
construir las premisas ciertas $P \rightarrow Q$ y Q y la conclusión falsa P. En este caso aparece sin más que la conclusión es falsa, pues es precisamente la proposición atómica P. 


**Ejemplo^^**. Se sugiere que de la proposición $P \rightarrow Q$ se podría inferir la proposición $\neg{P} \lor Q$. Se puede demostrar la validez de esta inferencia construyendo la tabla de inferencia apropiada.

\begin{align*}
\begin{tabular}{ c c c c c } 
 P & Q & $\neg{P}$ &  $P \rightarrow Q$ & $\neg{P} \lor Q$ \\
  \hline
 C & C & F & \textcolor{blue}{C} & \textcolor{blue}{C} \\ 
 C & F & F & F & F  \\
 F & C & C & \textcolor{red}{C} & \textcolor{red}{C}  \\ 
 F & F & C & \textcolor{red}{C} & \textcolor{red}{C}  \\ 
\end{tabular}
\end{align*}

Para poner de manifiesto la potencia de este método de análisis, será útil considerar un ejemplo más complicado en el que no es posible de antemano saber nada de su validez o no validez. Se considera el siguiente razonamiento matemático.

- Si $x=0$ y $y=z$, entonces $y>1$
- $y \ngtr 1$
- Por tanto, $y \ne z$.

Se desea saber si este razonamiento es válido. Aparecen en él tres proposiciones atómicas, que se simbolizan en la forma

- A = $x=0$
- B = $y=z$
- C = $y > 1$.

Puesto que cada proposición atómica puede ser verdadera o falsa, hay $2^{3}=8$ combinaciones de certeza y, por tanto, ocho lineas en la tabla de certeza.

Mediante los símbolos **A**, **B** y **C**, el razonamiento considerado se puede simbolizar

\begin{align*}
\textrm{ } & A \land B \rightarrow C \\
\textrm{ } & \neg{C} \\
& \cline{1-2} \\
\textrm{ } & \neg{B} \\
\end{align*}

**Tabla de certeza**

\begin{align*}
\begin{tabular}{ c c c c c c c } 
 A & B & C & $A \land B$ & $A \land B \rightarrow C$ & $\neg{C}$ & $\neg{B}$ \\
  \hline
 C & C & C & C & C & F & F  \\ 
 C & C & F & C & F & C & F  \\
 C & F & C & F & C & F & C  \\
 C & F & F & F & \textcolor{red}{C} & \textcolor{red}{C} & \textcolor{red}{C}  \\
 F & C & C & F & C & F & F  \\
 F & C & F & F & \textcolor{blue}{C}  & \textcolor{blue}{C}  & \textcolor{blue}{F}  \\
 F & F & C & F & C & F & C  \\
 F & F & F & F & \textcolor{red}{C} & \textcolor{red}{C} & \textcolor{red}{C}   \\
\end{tabular}
\end{align*}

Como indican las lineas en colores (azul y rojo), tres de las ochos lineas tienen dos premisas ciertas, pero como indica la linea con proposiciones de color azul, la conclusión no es cierta. Por lo tanto, el razonamiento es erróneo. 

